blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/Phal-Sovandy/Automata-Drawing-Tool/discussions
    about: Ask questions and get help from the community
  - name: Email Support
    url: mailto:phalsovandy007@gmail.com
    about: Contact the developer directly for support
